### ISSUE TITLE
Generate the geolocation of the user

### ISSUE THREAD

**Issue by vanikari** [connorleee/project-1#9]
## User Story
As a user, I want my location to be automatically accessed by the webpage.

## Acceptance Criteria
- [x] index.html has a check box to obtain permission for accessing the location
- [x] index.html also has a text box, 
     - [x] incase geolocation function is unable to access the user's location so the user can               input the location
     - [x] user doesn't want to use the geolocation services, so manually enter the location

**Comment by connorleee** [comment]
well done Vani
